version: '3'

services:
  web:
    image: ${IMAGE_NAME}:latest
    deploy:
      replicas: 1
      labels:
        xyz.tangerie.reverse_proxy.path: "/"
        xyz.tangerie.reverse_proxy.port: "8000"
        xyz.tangerie.reverse_proxy.server_name: "quotes.tangerie.xyz"
    # environment:
    #   - BASE_URL=/quotes
    networks:
      - nginx-proxy-overlay

networks:
  nginx-proxy-overlay:
    driver: overlay
    external: true