name: Build, Push & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
      uses: TangerieOrg/Workflows/.github/workflows/docker-build-push.yml@main
      with:
        image_name: discord-quotes
        registry_name: docker.tangerie.xyz
        ref: main
      secrets: inherit
    
  deploy:
    uses: TangerieOrg/Workflows/.github/workflows/docker-deploy.yml@main
    needs: 
      - build
    with:
      image_name: discord-quotes
      registry_name: docker.tangerie.xyz
      
    secrets: inherit